; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.2
	#esp32async/ESPAsyncWebServer@^3.8.1
	#esp32async/AsyncTCP@^3.4.9
    # Die AsyncTCP-Bibliothek muss auf die korrigierte Version gesetzt werden
    https://github.com/me-no-dev/AsyncTCP.git
    # Die ESPAsyncWebServer-Bibliothek muss auf die korrigierte Version gesetzt werden
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/RobTillaart/GY521.git
    # Library for MCP23017 I/O Extension
    adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.2
    # Library for INA3221 Voltage and Current Sensor
    https://github.com/adafruit/Adafruit_INA3221.git